version: "3"
services:
  latrappemelder:
    container_name: latrappemelder
    # image: denbeke/latrappemelder
    build: .
    ports:
      - "1234:1234"
    volumes: 
      - ./data:/latrappemelder