version: "3"
services:
  latrappemelder:
    container_name: latrappemelder
    # image: denbeke/latrappemelder
    build: .
    ports:
      - "1234:1234"
    environment:
      - APP_URL=${APP_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_DISABLE_TLS=${SMTP_DISABLE_TLS}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - ADMIN_MAIL=${ADMIN_MAIL}
    volumes: 
      - ./data:/latrappemelder
    restart: unless-stopped

